/*
 * Compile-time guard on the published type surface.
 *
 * `types/` is generated from the JSDoc in `lib/`, so a typedef that stops being
 * re-exported from `lib/index.js` silently disappears from the package's types
 * without any other check noticing. Every name below was exported before the
 * declarations were generated by TypeScript itself, and each is used both the
 * way consumers use it and in the position (type or value) it has to support.
 *
 * Checked by `npm run lint:types-api`. This file is never executed.
 */

import resolve = require("enhanced-resolve");
import {
	BaseFileSystem,
	Context,
	FileSystem,
	Plugin,
	PnpApi,
	ResolveCallback,
	ResolveContext,
	ResolveFunction,
	ResolveFunctionAsync,
	ResolveFunctionPromise,
	ResolveOptions,
	ResolveOptionsOptionalFS,
	ResolveRequest,
	Resolver,
	SyncFileSystem,
} from "enhanced-resolve";

// Exported types must be usable in a type position.
declare const baseFileSystem: BaseFileSystem;
declare const context: Context;
declare const fileSystem: FileSystem;
declare const plugin: Plugin;
declare const pnpApi: PnpApi;
declare const resolveCallback: ResolveCallback;
declare const resolveContext: ResolveContext;
declare const resolveFunction: ResolveFunction;
declare const resolveFunctionAsync: ResolveFunctionAsync;
declare const resolveFunctionPromise: ResolveFunctionPromise;
declare const resolveOptions: ResolveOptions;
declare const resolveOptionsOptionalFS: ResolveOptionsOptionalFS;
declare const resolveRequest: ResolveRequest;
declare const resolver: Resolver;
declare const syncFileSystem: SyncFileSystem;

// The exported classes must be usable as a type and as a constructor.
declare const cachedInputFileSystem: resolve.CachedInputFileSystem;
declare const cloneBasenamePlugin: resolve.CloneBasenamePlugin;
declare const logInfoPlugin: resolve.LogInfoPlugin;
declare const tsconfigPathsPlugin: resolve.TsconfigPathsPlugin;

new resolve.CachedInputFileSystem(baseFileSystem, 4000);
new resolve.CloneBasenamePlugin("described-resolve", "resolve");
new resolve.LogInfoPlugin("resolve");
new resolve.TsconfigPathsPlugin({});

// The module itself is callable, in each documented argument shape.
resolve("/parent", "./specifier", resolveCallback);
resolve(context, "/parent", "./specifier", resolveCallback);
resolve("/parent", "./specifier", resolveContext, resolveCallback);
resolve(context, "/parent", "./specifier", resolveContext, resolveCallback);

const sync: string | false = resolve.sync("/parent", "./specifier");
const promise: Promise<string | false> = resolve.promise(
	"/parent",
	"./specifier",
);

const created: ResolveFunctionAsync = resolve.create({});
const createdSync: ResolveFunction = resolve.create.sync({});
const createdPromise: ResolveFunctionPromise = resolve.create.promise({});

const factoryResolver: Resolver = resolve.ResolverFactory.createResolver({
	fileSystem,
});

resolve.forEachBail(
	[1, 2, 3],
	(item, callback) => callback(),
	(err, result) => {},
);

export {
	baseFileSystem,
	cachedInputFileSystem,
	cloneBasenamePlugin,
	context,
	created,
	createdPromise,
	createdSync,
	factoryResolver,
	logInfoPlugin,
	plugin,
	pnpApi,
	promise,
	resolveFunction,
	resolveFunctionAsync,
	resolveFunctionPromise,
	resolveOptions,
	resolveOptionsOptionalFS,
	resolveRequest,
	resolver,
	sync,
	syncFileSystem,
	tsconfigPathsPlugin,
};
